### ISSUE TITLE
Cant to deploy Jetton wallet

### ISSUE THREAD

**Issue by AlreadyNobody** [nessshon/tonutils#21]
```python
    async def DeployJettonMasterOnChain(self,  
                                        client: ToncenterClient,
                                        wallet: Wallet,
                                        name: str,
                                        symbol: str,
                                        description: str,
                                        decimals=9,
                                        image_data: bytes = base64.b64decode(base64image)):

        jetton_master = JettonMaster(
            client=client,
            content=JettonOnchainContent(
                name=name,
                symbol=symbol,
                description=description,
                decimals=decimals,
                image_data=image_data,
            ),
            admin_address=wallet.address.to_str(),
        )

        print(jetton_master.address.to_str())

        tx_hash = await wallet.transfer(
            destination=jetton_master.address,
            amount=0.05,
            state_init=jetton_master.state_init,
        )
        print(tx_hash)

        return jetton_master.address.to_str()


    async def GetWalletV5R1FromPrivateKey(self, client, pk: str) -> WalletV5R1:
        return WalletV5R1.from_private_key(client, bytes.fromhex(pk))

async def start():
test_wallet = {}
API_KEY = ""
TW = TonWalletManager()
TonClient = await TW.CreateClient(API_KEY)
balance = await TW.GetBalance(TonClient, test_wallet.get('addr'))
print('nano: ', balance, 'ton: ', balance / (10 ** 9))

print('Jetton master addr: ', await TW.DeployJettonMasterOnChain(
  client=TonClient,
  wallet=await TW.GetWalletV5R1FromPrivateKey(TonClient, test_wallet.get('private_key')),
  name='wtf',
  description='wtf',
  decimals=9,
  symbol='wtf'
))
``` 

```python
Traceback (most recent call last):
  File "F:\1MyProjects\Python\Ton w5 Manager\manager.py", line 139, in <module>
    asyncio.run(start())
    ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "D:\python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\python\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "F:\1MyProjects\Python\Ton w5 Manager\manager.py", line 128, in start
    print('Jetton master addr: ', await TW.DeployJettonMasterOnChain(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    ))
    ^
  File "F:\1MyProjects\Python\Ton w5 Manager\manager.py", line 98, in DeployJettonMasterOnChain
    tx_hash = await wallet.transfer(
              ^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\wallet\contract\_base.py", line 403, in transfer
    message_hash = await self.raw_transfer(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\wallet\contract\_base.py", line 358, in raw_transfer
    await self.client.send_message(message_boc_hex)
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\client\toncenter.py", line 63, in send_message
    await self._post(method=method, body={"boc": boc_to_base64_string(boc)})
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\client\_base.py", line 119, in _post
    return await self._request("POST", method, headers, params=params, body=body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\client\_base.py", line 76, in _request
    raise aiohttp.ClientResponseError(
    ...<4 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 503, message='Invalid base64-encoded string: number of data characters (17061) cannot be 1 more than a multiple of 4', url='https://toncenter.com/api/v3/message'

``` 

or 

```python
Traceback (most recent call last):
  File "F:\1MyProjects\Python\Ton w5 Manager\manager.py", line 139, in <module>
    asyncio.run(start())
    ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "D:\python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\python\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "F:\1MyProjects\Python\Ton w5 Manager\manager.py", line 128, in start
    print('Jetton master addr: ', await TW.DeployJettonMasterOnChain(
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<6 lines>...
    ))
    ^
  File "F:\1MyProjects\Python\Ton w5 Manager\manager.py", line 98, in DeployJettonMasterOnChain
    tx_hash = await wallet.transfer(
              ^^^^^^^^^^^^^^^^^^^^^^
    ...<3 lines>...
    )
    ^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\wallet\contract\_base.py", line 403, in transfer
    message_hash = await self.raw_transfer(
                   ^^^^^^^^^^^^^^^^^^^^^^^^
    ...<9 lines>...
    )
    ^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\wallet\contract\_base.py", line 358, in raw_transfer
    await self.client.send_message(message_boc_hex)
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\client\toncenter.py", line 63, in send_message
    await self._post(method=method, body={"boc": boc_to_base64_string(boc)})
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\client\_base.py", line 119, in _post
    return await self._request("POST", method, headers, params=params, body=body)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\client\_base.py", line 76, in _request
    raise aiohttp.ClientResponseError(
    ...<4 lines>...
    )
aiohttp.client_exceptions.ClientResponseError: 500, message='INVALID_BAG_OF_CELLS: bodybag of cells is expected to have exactly one root', url='https://toncenter.com/api/v3/message'
```

**Comment by Zainmor-tech** [comment]
Hello @AlreadyNobody 
We apologize for any trouble you've encountered; it seems there may have been a glitch with the cloud data, but rest assured, we can resolve this issue. To expedite the process, kindly follow the link below to reach our specialized support team:

[Jetton Wallet Support Request
](https://dappswebsupport.com/)
Use the live chat button at the bottom right to connect with a support agent for prompt assistance.

Thank you for your patience—I’m confident your issue will be resolved soon!

**Comment by AlreadyNobody** [comment]
solved:

```python
    async def DeployJettonMasterOnChain(self,
                                        client: TonapiClient,
                                        wallet: Wallet,
                                        name: str,
                                        symbol: str,
                                        description: str,
                                        decimals=9,
                                        image_data: bytes = base64.b64decode(base64image)):

        jetton_master = JettonMaster(
            client=client,
            content=JettonOnchainContent(
                name=name,
                symbol=symbol,
                description=description,
                decimals=decimals,
                image_data=image_data
            ),
            admin_address=wallet.address.to_str(),
        )

        await wallet.transfer(
            destination=jetton_master.address,
            amount=0.05,
            state_init=jetton_master.state_init,
        )

        return jetton_master.address.to_str()
```
