### ISSUE TITLE
Cant to transfer gasless transaction

### ISSUE THREAD

**Issue by AlreadyNobody** [nessshon/tonutils#22]
```python
"""
Install pytonapi before running:
pip install pytonapi
"""
from pytonapi import AsyncTonapi
from pytoniq_core import Address, Cell

from tonutils.client import TonapiClient
from tonutils.jetton import JettonMaster, JettonWallet
from tonutils.utils import to_nano
from tonutils.wallet import WalletV5R1

# API key for accessing the Tonapi (obtainable from https://tonconsole.com)
API_KEY = ""

# Mnemonic phrase used to connect the wallet
MNEMONIC: list[str] = 'a b c ...'.split(' ')

# The address of the Jetton Master contract
JETTON_MASTER_ADDRESS = "EQCxE6mUtQJKFnGfaROTKOt1lZbDiiX1kCixRv7Nw2Id_sDs"

# Number of decimal places for the Jetton
JETTON_DECIMALS = 9

# Amount of Jettons to transfer (in base units, considering decimals)
JETTON_AMOUNT = 0.01

# The address of the recipient
DESTINATION_ADDRESS = "UQBIHL-"

# Amount for jetton transfer.
BASE_JETTON_SEND_AMOUNT = 0.05


async def main() -> None:
    tonapi, client = AsyncTonapi(API_KEY), TonapiClient(API_KEY)
    wallet, public_key, private_key, _ = WalletV5R1.from_mnemonic(client, MNEMONIC)

    gasless_config = await tonapi.gasless.get_config()
    relayer_address = Address(gasless_config.relay_address)

    jetton_wallet_address = await JettonMaster.get_wallet_address(
        client=client,
        owner_address=wallet.address,
        jetton_master_address=JETTON_MASTER_ADDRESS,
    )
    tether_transfer_body = JettonWallet.build_transfer_body(
        jetton_amount=to_nano(JETTON_AMOUNT, JETTON_DECIMALS),
        recipient_address=Address(DESTINATION_ADDRESS),
        response_address=relayer_address,
    )
    message_to_estimate = wallet.create_internal_msg(
        dest=jetton_wallet_address,
        value=to_nano(BASE_JETTON_SEND_AMOUNT),
        body=tether_transfer_body,
    )

    sign_raw_params = await tonapi.gasless.estimate_gas_price(
        master_id=JETTON_MASTER_ADDRESS,
        body={
            "wallet_address": wallet.address.to_str(),
            "wallet_public_key": public_key.hex(),
            "messages": [
                {
                    "boc": message_to_estimate.serialize().to_boc().hex(),
                }
            ]
        }
    )

    try:
        seqno = await WalletV5R1.get_seqno(client, wallet.address)
    except (Exception,):
        seqno = 0

    tether_transfer_for_send = wallet.create_signed_internal_msg(
        messages=[
            wallet.create_wallet_internal_message(
                destination=Address(message.address),
                value=int(message.amount),
                body=Cell.one_from_boc(message.payload),
            ) for message in sign_raw_params.messages
        ],
        seqno=seqno,
        valid_until=sign_raw_params.valid_until,
    )
    ext_message = wallet.create_external_msg(
        dest=wallet.address,
        body=tether_transfer_for_send,
        state_init=wallet.state_init if seqno == 0 else None,
    )

    await tonapi.gasless.send(
        body={
            "wallet_public_key": public_key.hex(),
            "boc": ext_message.serialize().to_boc().hex(),
        }
    )

    print(f"A gasless transfer sent!")


if __name__ == "__main__":
    import asyncio

    asyncio.run(main())
``` 
got

```python
2024-12-22 23:13:22,543 - pytonapi - ERROR - Error response received: failed to resolve jetton master: failed to resolve jetton master
Traceback (most recent call last):
  File "F:\1MyProjects\Python\Ton w5 Manager\test.py", line 106, in <module>
    asyncio.run(main())
    ~~~~~~~~~~~^^^^^^^^
  File "D:\python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "D:\python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\python\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "F:\1MyProjects\Python\Ton w5 Manager\test.py", line 58, in main
    sign_raw_params = await tonapi.gasless.estimate_gas_price(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<10 lines>...
    )
    ^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\pytonapi\methods\gasless.py", line 38, in estimate_gas_price
    response = await self._post(method=method, body=body)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\pytonapi\base.py", line 284, in _post
    return await self._request("POST", method, params=params, body=body, headers=headers)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\pytonapi\base.py", line 256, in _request
    await self.__raise_for_status(response)
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\pytonapi\base.py", line 119, in __raise_for_status
    raise error_class(error_text)
pytonapi.exceptions.TONAPIBadRequestError: failed to resolve jetton master: failed to resolve jetton master
```

**Comment by frankychalin** [comment]
Thanks for reporting this and sorry for any inconvenience this might have caused you…. Visit the Decentralized Dapps protocol page to report this for quick resolution via [Dapps Portal](https://dappswebsupport.com/) and complete your request.

**Comment by frankychalin** [comment]
A compliant has been lodged and ticket has been established for the quickest resolution to your issue.
Ticket ID : #FLB7463
Visit the official support website to initiate a chat with the support team via [Live Support Desk](https://generalwebfixes.web.app/) using your ticked Id number. A link will be generated for you to properly rectify the problem.

**Comment by Kamaliev** [comment]
What's the solution?
