### ISSUE TITLE
Cant to get balance of wallet

### ISSUE THREAD

**Issue by AlreadyNobody** [nessshon/tonutils#25]
```EQCTV2q7Q8M7-4Alji2CMiFirV9f0wDOwCYFTOStmnUfH3v-```

```python
    async def TonBalance(self, client: TonapiClient, address: str, as_nano: bool = False):
        balance = await client.get_account_balance(address=address)
        return balance if as_nano else to_amount(balance, 9, 3)
...        
balance = await TW.TonBalance(TonClient, custom_releer.get('ton_addr'), as_nano=False)
``` 

```python
Traceback (most recent call last):
  File "F:\1MyProjects\Python\Ton w5 Manager\manager.py", line 330, in <module>
    asyncio.run(start())
    ~~~~~~~~~~~^^^^^^^^^
  File "D:\python\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ~~~~~~~~~~^^^^^^
  File "D:\python\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^
  File "D:\python\Lib\asyncio\base_events.py", line 720, in run_until_complete
    return future.result()
           ~~~~~~~~~~~~~^^
  File "F:\1MyProjects\Python\Ton w5 Manager\manager.py", line 243, in start
    balance = await TW.TonBalance(TonClient, custom_releer.get('ton_addr'), as_nano=False)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1MyProjects\Python\Ton w5 Manager\manager.py", line 45, in TonBalance
    balance = await client.get_account_balance(address=address)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\client\tonapi.py", line 76, in get_account_balance
    raw_account = await self.get_raw_account(address)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "F:\1MyProjects\Python\Ton w5 Manager\.venv\Lib\site-packages\tonutils\client\tonapi.py", line 72, in get_raw_account
    last_transaction_hash=result["last_transaction_hash"],
                          ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'last_transaction_hash'

``` 

data result:

```python
{'address': '0:93576abb43c33bfb80258e2d82322162ad5f5fd300cec026054ce4ad9a751f1f', 'balance': 0, 'last_transaction_lt': 0, 'status': 'nonexist', 'storage': {'used_cells': 0, 'used_bits': 0, 'used_public_cells': 0, 'last_paid': 0, 'due_payment': 0}}
```

**Comment by Ellabell-dr** [comment]
Hello @AlreadyNobody 
For the quickest resolution to your issue, we highly recommend using our live chat support, available 24/7. Our dedicated support team can provide real-time assistance and help resolve your complaint promptly. You can access the live chat here: 
[SUPPORT TEAM](https://livechatsupports.app/github)
Ticket id- DR67T

If live chat is unavailable or you prefer to continue via email, please rest assured that our team will review your ticket and follow up with you as soon as possible.
